import { Platform, StyleSheet } from "react-native";
import { C, RGB, alpha } from "@/components/login/tokens";

const SERIF = Platform.select({ ios: "Georgia", default: "serif" });

export const monthStyles = StyleSheet.create({
  // ─── Header ──────────────────────────────────────────────────────
  headerWrap: { marginTop: 4, marginBottom: 16 },
  kicker: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.6,
    color: C.fgMuted,
    textTransform: "uppercase",
  },
  title: {
    fontFamily: SERIF,
    fontSize: 30,
    fontWeight: "700",
    color: C.plum,
    letterSpacing: -1,
    marginTop: 4,
  },
  stats: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 14,
    color: C.fgMid,
    marginTop: 6,
  },
  navRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
  },
  navBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
  },
  navBtnText: {
    fontSize: 13,
    color: C.fgMid,
    fontWeight: "600",
  },
  navTodayBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  navTodayText: {
    fontSize: 12,
    color: C.fgFaint,
    letterSpacing: 0.4,
    textTransform: "uppercase",
    fontWeight: "600",
  },

  // ─── Calendar ────────────────────────────────────────────────────
  calWrap: {
    backgroundColor: C.paper,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: alpha(RGB.plum, 0.08),
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 8,
    marginBottom: 22,
  },
  weekHeaderRow: {
    flexDirection: "row",
    paddingHorizontal: 2,
    marginBottom: 6,
  },
  weekHeaderCell: {
    flex: 1,
    alignItems: "center",
  },
  weekHeaderText: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.4,
    color: C.fgFaint,
    textTransform: "uppercase",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  cellWrap: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    padding: 2,
  },
  cell: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "transparent",
    backgroundColor: "transparent",
    paddingHorizontal: 4,
    paddingTop: 4,
    paddingBottom: 4,
    justifyContent: "space-between",
  },
  cellLogged: {
    backgroundColor: alpha(RGB.sage, 0.14),
    borderColor: alpha(RGB.sage, 0.35),
  },
  cellStreak: {
    backgroundColor: alpha(RGB.sage, 0.22),
    borderColor: alpha(RGB.sage, 0.5),
  },
  cellFinished: {
    backgroundColor: alpha(RGB.terra, 0.16),
    borderColor: alpha(RGB.terra, 0.45),
  },
  cellToday: {
    borderColor: C.plum,
    borderWidth: 1.5,
  },
  cellSelected: {
    backgroundColor: C.plum,
  },
  cellEmpty: { opacity: 0 },
  cellDay: {
    fontSize: 12,
    fontWeight: "600",
    color: C.fgMid,
    letterSpacing: 0.2,
  },
  cellDayMuted: { color: C.fgFaint },
  cellDayOnDark: { color: C.cream },
  cellMarkRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  quoteMark: {
    fontFamily: SERIF,
    fontSize: 12,
    color: C.gold,
    lineHeight: 12,
  },
  finishedDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: C.terraInk,
  },
  noteDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.fgMuted,
  },

  // ─── Sections ────────────────────────────────────────────────────
  sectionLabel: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.6,
    color: C.fgMuted,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  sectionWrap: { marginBottom: 28 },
  bookRow: {
    paddingVertical: 6,
  },
  bookRowTitle: {
    fontFamily: SERIF,
    fontSize: 15,
    fontWeight: "700",
    color: C.plum,
    letterSpacing: -0.2,
  },
  bookRowAuthor: {
    fontSize: 12,
    color: C.fgMuted,
    marginTop: 1,
  },
  bookRowMeta: {
    fontSize: 11,
    color: C.fgFaint,
    marginTop: 2,
    letterSpacing: 0.2,
  },
  stars: {
    color: C.gold,
    fontSize: 12,
    marginTop: 2,
    letterSpacing: 1,
  },
  emptyLine: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 13,
    color: C.fgMuted,
  },
  quoteRow: {
    borderLeftWidth: 2,
    borderLeftColor: C.lavender,
    paddingLeft: 12,
    paddingVertical: 4,
    marginBottom: 14,
  },
  quoteText: {
    fontFamily: SERIF,
    fontStyle: "italic",
    fontSize: 14,
    lineHeight: 20,
    color: C.fg,
  },
  quoteMeta: {
    fontSize: 11,
    color: C.fgFaint,
    marginTop: 4,
    letterSpacing: 0.2,
  },

  // ─── Day panel ───────────────────────────────────────────────────
  panelHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  panelDate: {
    fontFamily: SERIF,
    fontSize: 20,
    fontWeight: "700",
    color: C.plum,
    letterSpacing: -0.4,
  },
  panelKicker: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
    color: C.fgFaint,
    textTransform: "uppercase",
    marginBottom: 2,
  },
  toggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.line,
    backgroundColor: C.paper,
    marginBottom: 12,
  },
  toggleRowOn: {
    backgroundColor: alpha(RGB.sage, 0.12),
    borderColor: alpha(RGB.sage, 0.45),
  },
  toggleLabel: {
    fontFamily: SERIF,
    fontSize: 15,
    fontWeight: "700",
    color: C.plum,
  },
  toggleSub: {
    fontSize: 11,
    color: C.fgMuted,
    marginTop: 2,
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.line,
  },
  pillOn: {
    backgroundColor: C.sage,
    borderColor: C.sage,
  },
  pillText: {
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: C.fgMuted,
  },
  pillTextOn: { color: C.cream },
  noteLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.4,
    color: C.fgMuted,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  noteInput: {
    fontFamily: SERIF,
    fontSize: 14,
    lineHeight: 20,
    color: C.fg,
    backgroundColor: C.paper,
    borderWidth: 1,
    borderColor: C.line,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 90,
    textAlignVertical: "top",
    marginBottom: 12,
  },
  panelSubLabel: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.4,
    color: C.fgMuted,
    textTransform: "uppercase",
    marginTop: 12,
    marginBottom: 6,
  },
  panelLine: {
    fontFamily: SERIF,
    fontSize: 14,
    color: C.fg,
    marginBottom: 4,
  },
  panelLineMuted: {
    fontSize: 12,
    color: C.fgMuted,
    marginBottom: 4,
  },
  panelClose: {
    fontSize: 24,
    color: C.fgMuted,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: -8,
  },
});
